### ISSUE TITLE
Build failed: 'GlyphRun' does not contain a definition for 'PixelsPerDip'

### ISSUE THREAD

**Issue by cregx** [BerndK/SvgToXaml#22] opened 2020-10-12 11:22 UTC
When I try to compile the project SvgToXaml I get the following error message: 'GlyphRun' does not contain a definition for 'PixelsPerDip'.

**Comment by BerndK** [comment] 2020-12-10 22:19
Try to install and use .Net 4.6.2 or newer like 4.7.x
does this help?
or use the precompiled one, see releases

**Comment by BerndK** [comment] 2020-12-14 11:14
Closed, is a
Duplicate of #24

**Closed by BerndK** 2020-12-14 11:14 UTC
